#!/bin/bash
# Usage guide for testing different images

echo "=== PotholeGrade-BD Pipeline - Multi-Image Testing ==="
echo ""
echo "You can now test the integrated pipeline with any image!"
echo ""
echo "USAGE:"
echo "  python test_integrated_pipeline.py --image <image_path>"
echo ""
echo "EXAMPLES:"
echo "  # Default image (test_pothole_2.jpg)"
echo "  python test_integrated_pipeline.py"
echo ""
echo "  # Test with specific image"
echo "  python test_integrated_pipeline.py --image data/test_pothole.jpg"
echo "  python test_integrated_pipeline.py --image data/test_pothole_3.jpg"
echo "  python test_integrated_pipeline.py --image data/test_pothole_4.jpg"
echo ""
echo "  # Test with your own image"
echo "  python test_integrated_pipeline.py --image path/to/your/image.jpg"
echo ""
echo "AVAILABLE TEST IMAGES:"
ls -1 /Users/niloypramanik/PotholeGrade-BD/data/test_pothole*.jpg 2>/dev/null | sed 's|.*/||' | sed 's|^|  - data/|'
echo ""
echo "TEST RESULTS EXAMPLE:"
echo "  - Detects all potholes in image"
echo "  - Calculates ROI area for each detection"
echo "  - Estimates depth from pixel intensity"
echo "  - Computes volume and asphalt mass"
echo "  - Assigns RPS (Repair Priority Score) Level 1-3"
echo ""
